# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Database'
target 'ParentalAccompaniment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParentalAccompaniment

  target 'ParentalAccompaniment-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParentalAccompanimentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ParentalAccompaniment-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParentalAccompaniment-tvOS


end
